site:
  title: Det-Lab Documentation Site
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://hungry-liskov-0501e4.netlify.com
  start_page: doc-coding::index.adoc
content:
  sources:
  - url: https://github.com/det-lab/doc-linux.git
    branches: master
  - url: https://github.com/det-lab/doc-coding.git
    branches: master
    start_path: docs
  #- url: https://github.com/det-lab/doc-python.git
  #  branches: master
ui:
  bundle:
    url: https://github.com/det-lab/doc-ui/releases/download/v3/ui-bundle.zip
    #url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
